{{- if .Values.metrics.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "zookeeper.fullname" . }}-metrics
  namespace: {{ template "zookeeper.namespace" . }}
  {{- if or .Values.metrics.ingress.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.metrics.ingress.annotations -}}
    {{ include "zookeeper.tplValue" ( dict "value" .Values.metrics.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "zookeeper.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.metrics.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "zookeeper.fullname" . }}-metrics
          servicePort: {{ .Values.metrics.service.port }}
  tls:
  - hosts:
    - {{ .Values.metrics.ingress.host }}


{{- end }}
